### ISSUE TITLE
To-do list 

### ISSUE THREAD

**Issue by MuhammedKpln** [MuhammedKpln/coban-package-manager#1]
- [ ] Multiple package installation/uninstallation/upgrade
- [ ] Http are not following download link ( packages can only be downloaded with direct link )
- [ ] Dependencies installation are in infinite loop ( kind )
